GET {{endpoint}}/ping/{{id}}

> {%
 client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 %}

###

GET {{endpoint}}/ping/0

> {%
 client.test("Request executed successfully", function() {
        client.assert(response.status === 500, "Response status is not 500");
    });
 %}

###

GET {{endpoint}}/v2/api-docs

###
